version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    networks:
      - intrabooking_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - intrabooking_net
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  intrabooking_net:
    external: true
