services:
  db:
    container_name: postgresdb
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: capstone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zaccaro
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app:
    container_name: intrabooking-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/capstone
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Zaccaro

      APP_DATASOURCE_MAX-POOL: "20"
      APP_DATASOURCE_MIN-IDLE: "5"
      APP_DATASOURCE_CONNECTION-TIMEOUT: "10000"
      APP_DATASOURCE_IDLE-TIMEOUT: "300000"
      APP_DATASOURCE_MAX-LIFETIME: "1800000"
      APP_DATASOURCE_LEAK-DETECTION-THRESHOLD: "300000"

      HEALTH_ALLOWED_IPS: "127.0.0.1,0:0:0:0:0:0:0:1"

volumes:
  postgres-data:
