---
- name: 1. Install Docker on all nodes (app and monitoring)
  hosts: all
  become: true
  roles:
    - docker

- name: 2. Deploy IntraBooking (app + Postgres)
  hosts: app
  become: true
  roles:
    - intrabooking

- name: 3. Deploy monitoring (Prometheus + Grafana)
  hosts: monitoring
  become: true
  roles:
    - monitoring
